server:
  port: ${SERVER_PORT:8081}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: pst21
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${APP_JWT_SECRET:B6BE2A94E42DFC80FDE81FA5956B6F7B438702C38DFD51DA8B35BB867A76BB73}
    expiration:
      milliseconds: ${APP_JWT_EXPIRATION_MILLISECONDS:180000}